//Padrão
GET http://localhost:3003/users
###
//filtro name
GET  http://localhost:3003/users?name=Maju
###
//
//Filtro Type
GET  http://localhost:3003/users/Teacher
###
//Order by name or type
GET  http://localhost:3003/users?sort=type&order=asc
###
//Limit and Pagination
GET http://localhost:3003/users/page?page=3
###
//All filters
GET GET http://localhost:3003/filters/users/Teacher?sort=type&order=ASC&limit=5
